package resolucao;

import busca.Nodo;

public class ViewResolucao extends javax.swing.JFrame {

    private int noAtual;
    private EstadoPuzzle caminho[];
    private int profundidade;

    public ViewResolucao(Nodo n) {
        this.setTitle("Profundidade: " + n.getProfundidade());
        initComponents();

        // Seta o resultado na tela
        EstadoPuzzle estado = (EstadoPuzzle) n.getEstado();
        taCaminho.setText(estado.formataExibir());

        // Cria um array com os nodos
        profundidade = n.getProfundidade();
        caminho = new EstadoPuzzle[profundidade + 1];
        for (int i = profundidade; i >= 0; i--) {
            caminho[i] = estado;
            n = n.getPai();
            if (n != null) {
                estado = (EstadoPuzzle) n.getEstado();
            }
        }

        noAtual = profundidade;
        this.setLocationRelativeTo(null);
    }

    public void exibir() {
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taCaminho = new javax.swing.JTextArea();
        btAntes = new javax.swing.JButton();
        btSuce = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resolução");

        taCaminho.setColumns(20);
        taCaminho.setRows(5);
        taCaminho.setEnabled(false);
        jScrollPane1.setViewportView(taCaminho);

        btAntes.setText("Antecessor");
        btAntes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAntesActionPerformed(evt);
            }
        });

        btSuce.setText("Sucessor");
        btSuce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuceActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btAntes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSuce)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAntes)
                    .addComponent(btSuce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        ViewPrincipal cont = new ViewPrincipal();
        cont.exibir();

        setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btAntesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAntesActionPerformed
        if (noAtual > 0) {
            noAtual--;
            taCaminho.setText(caminho[noAtual].formataExibir());
        }
    }//GEN-LAST:event_btAntesActionPerformed

    private void btSuceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuceActionPerformed
        if (noAtual < profundidade) {
            noAtual++;
            taCaminho.setText(caminho[noAtual].formataExibir());
        }
    }//GEN-LAST:event_btSuceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewResolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewResolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewResolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewResolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ViewResolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAntes;
    private javax.swing.JButton btSuce;
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taCaminho;
    // End of variables declaration//GEN-END:variables
}
